My room development
Lambda-School-Labs/lan-be-a pull request #86
Opened 2021-04-17 01:34 UTC by Devon-Brady

### Description
  Add description here
Set up routes models needed for my room feature.
  What was changed?
A few new files were created to support the new routes and models as well as new server end points
  Why does PR exist?
To push to main
  How do your changes do what is intended?
  Will a screenshot be helpful?

### Tests
  How was it tested?
I tested the endpoints with postman and Postgres using seeded and dummy data
### Reviewers
  2 reviewers required to merge to main. Must not merge your own pull request.

2021-04-17 01:48 UTC, Plofland commented on index.js
> +  console.log(req.user)
We can get rid of this

2021-04-17 01:51 UTC, Plofland commented on models/my-room-model.js
> +    // TODO: handle the case where a user has already liked a room
Let's turn this into a Trello care before it gets forgotten about.

2021-04-17 01:52 UTC, Plofland commented on package.json
> +		"sqlite3": "^5.0.2"
We won't be needing this dependency for the production DB.

2021-04-17 01:54 UTC, Plofland commented on routes/my-room-router.js
> +// TODO: add a room to a users rooms
Get rid of the word 'TODO' unless you're still working on these endpoints.

2021-04-17 01:55 UTC, Plofland requested changes
After you make some very minor changes, let's get it merged in.

2021-04-17 02:22 UTC, Plofland commented on routes/my-room-router.js
> +// TODO: add a room to a users rooms
I like the comments though

2021-04-19 16:44 UTC, gvicas17 requested changes, later dismissed
Besides getting rid of that console.log it looks good!

2021-04-19 16:44 UTC, gvicas17 commented on index.js
> +  console.log(req.user)
This console.log can be deleted.

2021-04-19 17:00 UTC, Plofland approved these changes
Thanks for making the changes. With the exception of the one console.log that Gabby found, it looks good to me.

2021-04-19 21:16 UTC, dustyfingers approved these changes

2021-04-19 21:19 UTC, dustyfingers approved these changes

2021-04-20 17:31 UTC, ialkamal approved these changes
Looks good. reviewed with Devon.

2021-04-20 17:32 UTC, merged

2021-04-20 17:32 UTC, gvicas17 approved these changes
Looks good!